<?php

/**
 * @file
 * This module allows you to add Pager blocks to navigate through entities.
 */

/**
 * Implements hook_views_api().
 * This one is used as the base to reduce errors when updating.
 */
function entity_pager_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'entity_pager') . '/views',
  );
}

/**
 * Implements hook_theme.
 * @return array
 */
function entity_pager_theme() {

  $themes = array();
  $themes['entity_pager'] = array(
    'variables' => array(
      'list' => array(),
    ),
    'template' => 'entity-pager',
  );
  return $themes;
}

/**
 * Implements template_preprocess_hook().
 * @param $vars
 */
function template_preprocess_entity_pager(&$vars) {
  drupal_add_css(drupal_get_path('module', 'entity_pager') . '/css/entity_pager.css');
}
