<?php

/**
 * @file
 * This module allows you to add Pager blocks to navigate through entities.
 */


/**
 * Implements hook_help().
 */
function entity_pager_help($path, $arg) {
  switch ($path) {
    case 'admin/help#entity_pager':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides next and previous navigation on entities.') . '<p>';
      $output .= '<p>' . t(' e.g.') . '<p>';
      $output .= '<p>' . ' &nbsp '. t(' < prev ').' &nbsp '.t(' All ').' &nbsp '.t(' next > ').'<p>';
      $output .= '<p>' . t('You can add multiple different navigation blocks on the same entity. This module combines Views, Blocks, Tokens and has its own internal intelligent advice system giving tips that are published to Watchdog (optionally). It is designed to run fast with the minimum of processing.');
      $output .= '<p>' . t('It is simple to use, allowing you can create Navigation blocks in a few seconds. For more complex pagers, it can combine with the Entity Reference module to create generic sub-navigation on related entities.');
      $output .= '<p>' . t(' e.g. navigate through a Brands products or go back to the Brand page itself.').'<p>';
      $output .= '<p>' . ' &nbsp '. t(' < prev ').' &nbsp '.t(' Pepsi ').' &nbsp '.t(' next > ').'<p>';

      $output .= '<p>' . t('see demonstration video at:  ??????');
      return $output;
  }
}

/**
 * Implements hook_views_api().
 * This one is used as the base to reduce errors when updating.
 */
function entity_pager_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'entity_pager') . '/views',
  );
}

/**
 * Implements hook_theme.
 * @return array
 */
function entity_pager_theme() {

  $themes = array();
  $themes['entity_pager'] = array(
    'variables' => array(
      'list' => array(),
    ),
    'template' => 'entity-pager',
  );
  return $themes;
}

/**
 * Implements template_preprocess_hook().
 * @param $vars
 */
function template_preprocess_entity_pager(&$vars) {
  drupal_add_css(drupal_get_path('module', 'entity_pager') . '/css/entity_pager.css');
}
